# Primary colors
[colors.primary]
background = "#161616"
foreground = "#ffffff"

# Search colors
[colors.search.matches]
foreground = 'CellBackground'
background = '#ee5396'

# Normal colors
[colors.normal]
black = '#262626'
magenta = '#ff7eb6'
green = '#42be65'
yellow = "#ffe97b"
blue = '#33b1ff'
red = '#ee5396'
cyan = '#3ddbd9'
white = '#dde1e6'

# Bright colors
[colors.bright]
black = '#393939'
magenta = '#ff7eb6'
green = '#42be65'
yellow = "#ffe97b"
blue = '#33b1ff'
red = '#ee5396'
cyan = '#3ddbd9'
white = '#ffffff'
[font]
size = 12.0

[font.bold]
family = "UbuntuMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font Propo"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[window]
decorations = "none"
opacity = 0.9

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 1
y = 1



# [[keyboard.bindings]]
# key = "Left"
# mods = "Alt"
# chars = "\u001bb"
#
# [[keyboard.bindings]]
# key = "Right"
# mods = "Alt"
# chars = "\u001bf"

