[pyprland]
plugins = [
    "scratchpads",
]

[scratchpads.terminals]
animation = "fromRight"
margin = 50
size = "95% 60%"
max_size = "1920px 100%"

[scratchpads.term]
command = "kitty --class kitty-dropterm --directory ~/git_clones claude"
class = "kitty-dropterm"
use = "terminals"
